taxonomy_scheduler.settings:
  type: config_object
  label: 'Taxonomy Scheduler settings'
  mapping:
    initialized:
      type: integer
      label: 'Initialized'
    vocabularies:
      type: sequence
      label: 'Vocabularies'
      sequence:
        type: string
        label: 'vid'
    field_name:
      type: string
      label: 'Field name'
    field_label:
      type: string
      label: 'Field label'
    field_required:
      type: integer
      label: 'Field required'
